spring:  
  application:
    name: abobora

zuul:
  routes:
    users:
      path: /abobora/**
      serviceId: ABOBORA
    auth:
      path: /auth/**
      serviceId: AUTHSERVER
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
server:
  port: 8765
